name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish to mooncakes.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: cogna-dev/moonbit-actions/setup@v0

      - name: Publish package
        uses: cogna-dev/moonbit-actions/publish@v0.1.2
        with:
          token: ${{ secrets.MOONCAKES_TOKEN }}
